
services:
  docker_status:
    image: avt0x/docker-dashboard:latest
    container_name: docker-dashboard
    hostname: dev
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
